version: '3'

services:
  neo4j:
    image: neo4j:4.4-community
    container_name: neo4j
    privileged: true
    restart: always

    environment:
      - NEO4J_AUTH=neo4j/regy
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS='["apoc"]'

    ports:
      - "7474:7474"
      - "7687:7687"

    volumes:
      - "./data:/var/lib/neo4j/data"
      - "./logs:/var/lib/neo4j/logs"
      - "./import:/var/lib/neo4j/import"
      - "./plugins:/var/lib/neo4j/plugins"
      - "./conf:/var/lib/neo4j/conf"