version: "2.1"
services:
  jobmanager:
    image: flink
    expose:
      - "6123"
    ports:
      - "8088:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./job/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./log:/opt/flink/log
    restart: always
    networks:
      - nexdata_nexdata

  taskmanager:
    image: flink
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./task/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml
      - ./log:/opt/flink/log
    restart: always
    networks:
      - nexdata_nexdata

networks:
  nexdata_nexdata:
    external: true
